- name: expense
  hosts: local
  connection: local
  vars: 
    nexus:
    - mysql
    - backend
    - frontend
  tasks:
  - name: install boto3 and botocore
    ansible.builtin.pip:
      name:
         - boto3
         - botocore
      executable: pip3.9 
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      name: "{{item}}" 
      vpc_subnet_id: subnet-00a686d0e79dedb31
      instance_type: t3.micro
      security_group: sg-0201d0d466a3135e4
      image_id: ami-09c813fb71547fc4f
      wait: true
    Loop: "{{nexus}}"
    register: benos
  - name: display vars
    ansible.builin.debug:
      msg: "display name is {{nexus}}"
  
    